# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
